<template>
  <div class="max-w-2xl mx-auto mt-10">
    <BaseCardPixel title="Craft a New Role" :hoverable="false">

        <!-- Step 1: Input -->
        <div v-if="step === 1" class="space-y-6">
            <div>
                <label class="block font-pixel text-xs uppercase mb-2">Role Title</label>
                <input v-model="form.title" type="text" placeholder="e.g. Senior Frontend Engineer" class="w-full p-3 border-2 border-pixel-border font-sans focus:outline-none focus:shadow-pixel">
            </div>

            <div>
                <label class="block font-pixel text-xs uppercase mb-2">Focus Area / Context</label>
                <textarea v-model="form.context" rows="3" placeholder="I want to focus on Vue 3, performance optimization, and accessibility." class="w-full p-3 border-2 border-pixel-border font-sans focus:outline-none focus:shadow-pixel"></textarea>
            </div>

            <div class="flex justify-end">
                <BaseButtonPixel @click="generateRoadmap" :disabled="!form.title">
                    Generate Roadmap ✨
                </BaseButtonPixel>
            </div>
        </div>

        <!-- Step 2: Loading -->
        <div v-if="step === 2" class="py-12 text-center">
            <div class="inline-block animate-bounce text-4xl mb-4">🧙‍♂️</div>
            <h3 class="font-pixel text-lg">Consulting the Archives...</h3>
            <p class="text-sm text-slate-500 mt-2">Generating phases and quests for "{{ form.title }}"</p>
        </div>

        <!-- Step 3: Preview -->
        <div v-if="step === 3" class="space-y-6">
             <div class="bg-slate-50 p-4 border-2 border-pixel-border text-center">
                 <div class="text-4xl mb-2">{{ generatedRole.icon }}</div>
                 <h2 class="font-pixel text-xl">{{ generatedRole.title }}</h2>
                 <p class="text-sm text-slate-600">{{ generatedRole.description }}</p>
             </div>

             <div>
                 <h4 class="font-pixel text-sm uppercase mb-3">Proposed Journey</h4>
                 <div class="space-y-3">
                     <div v-for="(phase, i) in generatedRole.phases" :key="i" class="flex gap-3 items-center p-3 border border-slate-200 bg-white">
                         <div class="bg-slate-100 w-6 h-6 place-items-center grid text-xs font-bold">{{ i + 1 }}</div>
                         <div>
                             <p class="font-bold text-sm">{{ phase.title }}</p>
                             <p class="text-xs text-slate-500">{{ phase.description }}</p>
                         </div>
                     </div>
                 </div>
             </div>

             <div class="flex justify-between mt-8">
                 <BaseButtonPixel variant="outline" @click="step = 1">Back</BaseButtonPixel>
                 <BaseButtonPixel variant="success" @click="confirmCreation">Start Quest ⚔️</BaseButtonPixel>
             </div>
        </div>

    </BaseCardPixel>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { useRolesStore } from '@/stores/roles.store';
import BaseCardPixel from '@/components/ui/pixel/BaseCardPixel.vue';
import BaseButtonPixel from '@/components/ui/pixel/BaseButtonPixel.vue';

const router = useRouter();
const rolesStore = useRolesStore();
const step = ref(1);

const form = reactive({
    title: '',
    context: ''
});

const generatedRole = ref<any>(null);

function generateRoadmap() {
    step.value = 2;
    // Simulate AI delay
    setTimeout(() => {
        generatedRole.value = {
            id: 'new_' + Date.now(),
            title: form.title,
            description: form.context || 'Custom learning path generated by AI.',
            icon: '🧪',
            level: 'Custom',
            totalPhases: 3,
            completedPhases: 0,
            progress: 0,
            isActive: true,
            createdAt: new Date(),
            phases: [
                { title: 'Phase 1: Basics', description: 'Core concepts and syntax.', steps: [] },
                { title: 'Phase 2: Application', description: 'Building real projects.', steps: [] },
                { title: 'Phase 3: Mastery', description: 'Advanced optimization.', steps: [] }
            ]
        };
        step.value = 3;
    }, 2000);
}

function confirmCreation() {
    rolesStore.createRole(generatedRole.value);
    router.push({ name: 'roles' });
}
</script>
